name: CI

on: [workflow_dispatch, push, pull_request]

permissions:
  contents: read
  
jobs:

  test:
  
    strategy:
      matrix:
        version: ['7.3', '7.4', '8.0', '8.1', '8.2']
        
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.version}}
          extensions: dom, mbstring, tidy
          ini-values: memory_limit=-1

      - name: PHP lint
        run: find . -path ./vendor -prune -o -type f -name '*.php' ! -name "test_with_parse_error.php" -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
  
      - name: Start built-in PHP server
        run: nohup php -S localhost:8080 -t test/site > php-server.log 2>&1 &
  
      - name: Test
        run: php test/all_tests.php
             
      - name: Display Server Log 
        run: cat php-server.log
